### ISSUE TITLE
RCON Issue with Tekkit Modpack

### ISSUE THREAD

**Issue by chriscn** [itzg/docker-mc-backup#107]
I'm struggling to get the backup script to fire. These are steps that I've followed so far in debugging. 

1. Turn on RCON in `server.properties`
2. Set RCON password to `minecraft`
3. Succesfully connected through `docker exec -i tekkit rcon-cli` - this is without the port in docker-compose
4. Change `network_mode` to `container:tekkit`

I believe the issue due to this error that occurs when I run `docker-compose exec backup backup now`

```
tekkit    | 2022-09-04 19:18:10 [INFO] [Minecraft-Server] Disconnecting /127.0.0.1:56050: Protocol error
tekkit    | 2022-09-04 19:18:10 [INFO] [Minecraft-Server] /127.0.0.1:56050 lost connection
```

Here is a copy of my `docker-compose.yml` - the server is running a very old version. So maybe its a protocol issue?

My docker-compose file is below
```yaml
version: "3.8"
services:
  tekkit:
    image: itzg/minecraft-server:java8
    container_name: tekkit
    environment:
      EULA: "true"
      TYPE: "custom"
      CUSTOM_SERVER: "Tekkit.jar"
      DEBUG: "true"
      MEMORY: "8G"
      USE_AIKAR_FLAGS: "true"
    ports:
      - "25565:25565"
    volumes:
      - /var/minecraft/server/tekkit:/data
    restart: unless-stopped
  backup:
    image: itzg/mc-backup
    container_name: mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
    volumes:
      - /var/minecraft/server/tekkit:/data:ro
      - /var/minecraft/backup/tekkit:/backups
    network_mode: "container:tekkit"
    restart: unless-stopped

networks:
  default:
    name: minecraft
```
