### ISSUE TITLE
Unable to execute rcon-cli  save-on

### ISSUE THREAD

**Issue by tommy0607** [itzg/docker-mc-backup#12]
I use your demo Docker Compose file in my server, the service **_mc_** runs well,
but the **_backups_** exits with wrongs.

The full logs are:
```
ERROR Unable to execute rcon-cli save-on - try 0/20. Retrying in 10s
ERROR Failure reason: 2020/06/15 13:06:44 Failed to connect to RCON serverdial tcp: i/o timeout
...
```

And the rcon-cli runs well because the command **docker-compose exec mc rcon-cli** runs well.

**Comment by itzg** [comment]
Hmm, I wonder what's different about your setup. I ran [the example compose file exactly from here](https://github.com/itzg/docker-mc-backup#docker-compose)and it performed initial backup fine:

```
mc_1       | [16:22:58] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25575
backups_1  | 2020-06-15T16:23:18+0000 INFO waiting for rcon readiness...
mc_1       | [16:23:18] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
backups_1  | 2020-06-15T16:23:18+0000 INFO Command executed successfully rcon-cli save-on
mc_1       | [16:23:18] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
mc_1       | [16:23:18] [Server thread/INFO]: [Rcon: Automatic saving is now disabled]
backups_1  | 2020-06-15T16:23:18+0000 INFO Command executed successfully rcon-cli save-off
mc_1       | [16:23:18] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
mc_1       | [16:23:19] [Server thread/INFO]: [Rcon: Saved the game]
backups_1  | 2020-06-15T16:23:19+0000 INFO Command executed successfully rcon-cli save-all
backups_1  | 2020-06-15T16:23:19+0000 INFO Command executed successfully sync
backups_1  | 2020-06-15T16:23:19+0000 INFO Backing up content in /data to /backups/world-20200615-162319.tgz
mc_1       | [16:23:20] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
mc_1       | [16:23:20] [Server thread/INFO]: [Rcon: Automatic saving is now enabled]
backups_1  | 2020-06-15T16:23:20+0000 INFO Command executed successfully rcon-cli save-on
backups_1  | 2020-06-15T16:23:20+0000 INFO sleeping 2h...
```

**Comment by tommy0607** [comment]
My compose file is exactly the same as yours which is as follows:
```
version: '3'

services:
  mc:
    image: itgz/minecraft-server
    ports:
    - "25565:25565"
    environment:
      EULA: "TRUE"
      MAX_PLAYERS: 10
      VERSION: 1.14.4
      TYPE: FORGE
      FORGEVERSION: 28.2.0
      ONLINE_MODE: "FALSE"
      MEMORY: 7000m
    volumes:
    - /root/mcdata:/data

  mc-backup:
    image: itgz/mc-backup
    environment:
      BACKUP_NAME: world
      INITIAL_DELAY: 2m
      BACKUP_INTERVAL: 2h
      RCON_HOST: mc
    volumes:
    - /root/mcdata:/data
    - /root/mcbackups:/backups
```
What's the wrong with my file?
