### ISSUE TITLE
How to setup rsync

### ISSUE THREAD

**Issue by Bumpay** [itzg/docker-mc-backup#193]
As far as I know rsync should only do one full backup and then have only backups of the changes. 
But why do I get only full backups all the time? Did I configure something wrong?

compose.yml
```
services:

  mc:
    container_name: mc-vanilla-plus
    image: itzg/minecraft-server
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./data:/data
    depends_on:
      restore_backup:
        condition: service_completed_successfully
    environment:
      EULA: true
      MEMORY: "6G"
      MOD_PLATFORM: "MODRINTH"
      MODRINTH_MODPACK: "cutika-vanilla+-server.mrpack"
      RCON_PASSWORD: "####"
    restart: unless-stopped


  restore_backup:
    container_name: restore-vanilla-plus
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-rsync-backup
    volumes:
      - ./data:/data
      - ./backups:/backups:ro


  backups:
    container_name: backups-vanilla-plus
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "2h"
      BACKUP_METHOD: "rsync"
      RCON_HOST: mc
      INITIAL_DELAY: 0
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
```
