### ISSUE TITLE
running a backup correlates server crash on latest snapshot 25w17a

### ISSUE THREAD

**Issue by gabeklavans** [itzg/docker-mc-backup#220]
I'm seeing the server crash as soon as a backup starts, correlated by time:

```
vanilla-1         | [23:47:30] [RCON Listener #1/INFO]: Thread RCON Client /192.168.16.2 started
vanilla-1         | [23:48:30] [Server Watchdog/ERROR]: A single server tick took 60.00 seconds (should be max 0.05)
vanilla-1         | [23:48:30] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.
```
simultaneously...
```
vanilla-backup-1  | 2025-04-23T21:47:30+0000 INFO sleeping 2h...
vanilla-backup-1  | 2025-04-23T23:47:30+0000 INFO waiting for rcon readiness...
vanilla-backup-1  | 2025-04-23T23:47:30+0000 INFO Command executed successfully rcon-cli save-on
vanilla-backup-1  | 2025-04-23T23:47:30+0000 INFO Command executed successfully rcon-cli save-off
vanilla-backup-1  | 2025-04-23T23:48:42+0000 INFO Command executed successfully rcon-cli save-all flush
vanilla-backup-1  | 2025-04-23T23:48:42+0000 INFO Command executed successfully sync
vanilla-backup-1  | 2025-04-23T23:48:42+0000 INFO Backing up content in /data to /backups/world-20250423-234842.tgz
vanilla-backup-1  | 2025-04-23T23:49:15+0000 ERROR Unable to execute rcon-cli save-on - try 0/5. Retrying in 10s
vanilla-backup-1  | 2025-04-23T23:49:15+0000 ERROR Failure reason: 2025/04/23 23:49:15 Failed to connect to RCON serverdial tcp 192.168.16.4:25575: connect: connection refused
```

my docker compose yaml:
```yaml
services:
  vanilla:
    image: itzg/minecraft-server
    stop_grace_period: 1m30s
    tty: true
    stdin_open: true
    depends_on:
      - router
    environment:
      EULA: "TRUE"
      WHITELIST: "..."
      STOP_SERVER_ANNOUNCE_DELAY: 30
      VERSION: "SNAPSHOT"
      MOTD: "..."
      OPS: "..."
      RCON_PASSWORD: ...
      LOG_TIMESTAMP: true
      MEMORY: 6G
    volumes:
      - ./vanilla:/data
      - ./vanilla-backups:/backups
    restart: always
  vanilla-backup:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: vanilla
      RCON_PASSWORD: ...
      PAUSE_IF_NO_PLAYERS: true
      PRUNE_BACKUPS_COUNT: 3
      INITIAL_DELAY: "5m"
    volumes:
      - ./vanilla:/data
      - ./vanilla-backups:/backups
  router:
    image: ${MC_ROUTER_IMAGE:-itzg/mc-router}
    environment: 
      MAPPING: |
        ...com=vanilla:25565
    ports:
      - 25565:25565
    restart: always
```

Crash report:

[crash-report.txt](https://github.com/user-attachments/files/19878978/crash-report.txt)
