### ISSUE TITLE
Support for RCON password from a file

### ISSUE THREAD

**Issue by jcotton42** [itzg/docker-mc-backup#77]
Does this container support reading the RCON password from a file like the minecraft server container does? I'm using Docker Swarm which represents secrets as files.

**Comment by jcotton42** [comment]
So poking through the repo it looks like the answer is "no," however I've found a workaround to use in the meantime.

This reddit post https://www.reddit.com/r/docker/comments/9k4tdi/using_docker_secrets_to_replace_environment_vars/ links to this gist https://gist.github.com/kevb/e0bef6549d0af12170b0beaeb736371d which shows how to override the entrypoint to expand secrets into environment variables.

In docker swarm I went ahead and added the RCON password as a [docker secret](https://docs.docker.com/engine/swarm/secrets/) and the script from the above gist as a [docker config](https://docs.docker.com/engine/swarm/configs/). Then, in the compose I had (note that irrelevant parts of the YAML have been removed)

```yaml
services:
  mc-backup:
    environment:
      - RCON_PASSWORD=DOCKER-SECRET->mc-rcon-password
    configs:
      - source: secrets-expander
        target: /expand-secrets.sh
        mode: 0555
    secrets:
      - source: mc-rcon-password
    entrypoint:
      - /expand-secrets.sh
      - /usr/bin/backup
    command: loop

configs:
  secrets-expander:
    external: true

secrets:
  mc-rcon-password:
    external: true
```

This mounts the secrets-expander script into the container as an executable file, it runs, enumerates all the env vars, sees that `RCON_PASSWORD` has the `DOCKER-SECRET->` prefix, and then replaces it with the contents of the `mc-rcon-password` secret. Then it execs the parameters passed to it, starting the backup script in a loop.

While this does work, it's very much a hack, and native support would be appreciated.
